name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

permissions:
  contents: write # Required to commit the report to the gh-pages branch
  pages: write # Required if deploying directly to GitHub Pages
  id-token: write # Required for secure OIDC deployment

jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    container:
      # https://mcr.microsoft.com/en-us/artifact/mar/playwright/about
      image: mcr.microsoft.com/playwright:v1.60.0-noble-amd64 # Pin to match your package.json Playwright version

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Run Playwright tests
        run: npm run test:ci
      - uses: actions/upload-artifact@v7
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      # 1. Deploy the report folder to GitHub Pages
      - name: Deploy Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./playwright-report # Default playwright folder

      # 2. Print a clickable link directly into the workflow output
      - name: Write Link to GitHub Summary
        if: always()
        run: |
          echo "### 🎭 [View Live Playwright Report](https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/) 🎭" >> $GITHUB_STEP_SUMMARY
